config/routes.rb
Rails.application.routes.draw do

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  
  post 'docs/save' => 'docs#save'
  
  get 'home' => 'static_pages#home'

  get 'contact' => 'static_pages#contact'

  get 'about' => 'static_pages#about'

  resources :categories
  resources :users
  resources :docs

  root 'static_pages#home'

end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :categories
  has_many :categories
end

app/models/doc.rb
class Doc < ActiveRecord::Base
  belongs_to :categories
  validates :title , presence: true, uniqueness: true
  validates :author , presence: true
  validates :description , presence: true
  validates :categories_id , presence: true
  
   # It returns the docs whose titles contain one or more words that form the query
  def self.search(query)
    # where(:title, query) -> This would return an exact match of the query
    where("title like ?", "%#{query}%") 
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save {self.email = email.downcase }
  validates :name , presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email , presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  def ensure_logged
    unless logged_in?
    flash[:danger] = "Please log in"
      redirect_to login_path
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :ensure_logged
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :categories_id)
    end
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
  before_action :ensure_logged
  def index
    if params[:search]
      @files = Doc.search(params[:search]).order("created_at DESC")
    else
      @files = Doc.order("created_at DESC")
    end
  end

  def new
    @file = Doc.new(params[:doc_params])
  end
  
  def save
    uploaded_io = params[:doc][:filename]
    @path = File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'wb') do |file|
    file.write(uploaded_io.read)
    end
    file = params[:doc]
    newfile = Doc.new()
    newfile.title = file[:title]
    newfile.author = file[:author]
    newfile.categories_id = file[:categories_id]
    newfile.description = file[:description]
    newfile.path = File.join(Rails.root, "public/uploads",uploaded_io.original_filename)
    newfile.filename = uploaded_io.original_filename
    newfile.save
    redirect_to docs_path
  end
  
  private

  def doc_params
    params.require(:doc).permit(:author, :description, :title, :categories_id, :filename, :path)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end
  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def contact
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_logged
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
    def user_params
      params.require(:user).permit(:name, :email, :cpf, :password,
                                   :password_confirmation, :isadministrator)
    end
  end
  
  
 
  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :cpf, :password,
                                   :password_confirmation, :isadministrator)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = "UNASP File Manager App"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  def logged_in?
    !current_user.nil?
  end
  def is_administrator?
    if logged_in?
    current_user.isadministrator
    end
  end
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :categories_id %><br>
    <%= f.text_field :categories_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<% provide(:title, 'Edit Category') %>
<h1>Edit Category</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@category) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      
      <label>General Category</label>
      <%= f.collection_select :categories_id, Category.all, :id, :name, {}, {class: 'form-control'} %>
      
      <%= f.submit "Update", class: "btn btn-primary" %>

    <% end %>
  </div>
</div>
<%= link_to 'Back', categories_path, class: "btn" %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Categories</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Categories</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= Category.find_by(id: category.categories_id).name %></td>
        <div class="btn-group btn-group-justified">
          <td><%= link_to 'Show', category, class: "btn btn-primary" %></td>
        <td><%= link_to 'Edit', edit_category_path(category), class: "btn btn-warning" %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
        </div>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path, class: "btn btn-primary" %>

app/views/categories/new.html.erb
<% provide(:title, 'New Category') %>
<h1>New Category</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@category) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      
      <label>General Category</label>
      <%= f.collection_select :categories_id, Category.all, :id, :name, {}, {class: 'form-control'} %>
      
      <%= f.submit "create", class: "btn btn-primary" %>

    <% end %>
  </div>
</div>
<%= link_to 'Back', categories_path, class: "btn" %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Categories:</strong>
  <%= Category.find_by(id: @category.categories_id).name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/docs/index.html.erb
<h1>Listings Documents</h1>
<table class="table table-striped table-hover">
  <% if logged_in? %>
      <% unless is_administrator? %>
      <%= form_tag(docs_path, :method => "get", class: "form-control") do %>
      <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Search Docs" %>
      <!-- In order to have the "search" icon int the button, we need to use plain HTML instead 
           of using a Rails form helper -->
      <button type="submit" class="btn btn-default">Search</button>
  <% end %>
  <% end %>
  <% end %>
  <%= pie_chart Doc.group(:categories_id).count %>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Description</th>
      <th>Categorie</th>
      <th>File</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @files.each do |file| %>
    <tr>
      <td><%= file.title %></td>
      <td><%= file.author %></td>
      <td><%= file.description %></td>
      <td><%= Category.find_by(id: file.categories_id).name %></td>
      <td><%= link_to file.filename,'/uploads/'+file.filename %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<p><%= link_to "New", new_doc_path , class: "btn btn-primary" %></p>

app/views/docs/new.html.erb
<h1>File Uploader</h1>
<%= form_for @file, :url => url_for(:controller => 'docs', :action => 'save') do |f| %>
<p>
  <label>Title:</label> <br/>
  <%= f.text_field :title, class: "form-control" %>
</p>
<p>
  <label>Author:</label> <br/>
  <%= f.text_field :author, class: "form-control" %>
</p>
<p>
  <label>Description</label> <br/>
  <%= f.text_field :description, class: "form-control" %>
</p>
<p>
  <label>Category</label> <br/>
  <%= f.collection_select(:categories_id, Category.all, :id, :name, {}, {class: 'form-control'}) %>
</p>




<p><label>Select the file:</label></br>
<%= f.file_field 'filename', class: "form-control" %></p>
<p><%= submit_tag "Save", class: "btn btn-primary" %>
<% end %>

app/views/docs/save.html.erb
<h1>Docs#save</h1>
<p>Find me in app/views/docs/save.html.erb</p>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <p>Made by a bunch of geeks from UNASP</p>
  </small>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <%= link_to "UNASP Files", root_path,  id: "logo", class: "navbar-brand" %>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><%= link_to "Home", root_path %></li>
                    <li><%= link_to "Contact", contact_path %></li>
                    <li><%= link_to "About", about_path %></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                  <% if logged_in? %>
                  <li><p class="nav btn">Hello <%= current_user.name %>!</p></li>
                  <% unless is_administrator? %>
                  <li><%= link_to "Categories", categories_path %></li>
                  <li><%= link_to "Documents", docs_path %></li>
                  <% else %>
                  <li><%= link_to "Users", users_path %></li>
                  <% end %>
                  <li><%= link_to "Log out", logout_path, method: "delete" %></li>
                  <% else %>
                  <li><%= link_to "Login", login_path %></li>
                  <% end %>
                </ul>
            </div>
        </div>
    </div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
  <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
<%= yield %>
<%= render 'layouts/footer' %>
</div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<h1>About</h1>
<p>There is nothing to tell about it, what about you tell more about you?</p>

app/views/static_pages/contact.html.erb
<h1>Contact</h1>
<p>There is still not way to contact us. Sorry for that.</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<h1>Home</h1>
<p>This project was made by the students of the computer science's seventh semester</p>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, 'Editing User') %>
<h1>Editing User</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>


      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
      
      <%= f.label :cpf %>
      <%= f.text_field :cpf, class: 'form-control' %>
      
      <label>Administrator?</label>
      <div class="form-control">
        <%= f.check_box :isadministrator %>
      </div>
      

      <%= f.submit "Update User", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>
<%= link_to 'Show', @user, class: "btn"%> |
<%= link_to 'Back', users_path, class: "btn" %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>CPF</th>
      <th>Email</th>
      <th>Administrador</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.cpf %></td>
        <td><%= user.email %></td>
        <td><%= user.isadministrator %></td>
        <div class="btn-group btn-group-justified">
          <td><%= link_to 'Show', user, class: "btn btn-primary" %></td>
        <td><%= link_to 'Edit', edit_user_path(user), class: "btn btn-warning" %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
        </div>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path, class: "btn btn-primary" %>

app/views/users/new.html.erb
<% provide(:title, 'User Registration') %>
<h1>User Registration</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>


      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
      
      <%= f.label :cpf %>
      <%= f.text_field :cpf, class: 'form-control' %>
      
      <label>Administrator?</label>
      <div class="form-control">
        <%= f.check_box :isadministrator %>
      </div>

      <%= f.submit "Create new account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>
<%= link_to 'Back', users_path, class: "btn" %>

app/views/users/show.html.erb
<% provide(:title, @user.name)  %>
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user), class: "btn" %> |
<%= link_to 'Back', users_path, class: "btn" %>